### ISSUE TITLE
Kanban board Full_stack_project

### ISSUE THREAD

**Issue by jaamanu** [eerapheal/Full_stack_project#16]
In this project we are a team of four, kindly find the project link attached below
https://github.com/eerapheal/Full_stack_project/projects/1

<img width="1435" alt="Screenshot 2023-03-10 at 10 09 58" src="https://user-images.githubusercontent.com/98466955/224259814-82ad87a9-1954-459e-8a26-dd3b7ec28864.png">
<img width="1430" alt="Screenshot 2023-03-10 at 10 10 18" src="https://user-images.githubusercontent.com/98466955/224259849-5a9c05bb-ca2e-4f3d-9fb6-8c4b4ee5d64e.png">

<img width="1440" alt="Screenshot 2023-03-10 at 10 10 29" src="https://user-images.githubusercontent.com/98466955/224259881-ab4fdd36-8076-4793-999f-90540751e2f1.png">

Add description for all issues

**Comment by Meltrust** [comment]
Hi @jaamanu,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been assigned✔️
- All tasks have paintings ✔️ 
- The paintings are fair ✔️  

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

According to the [project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md):

![image](https://user-images.githubusercontent.com/57421823/224259879-52dc0a5a-fbf0-4361-9175-6f957dc2e6ce.png)

At the time of this review, none of the tasks have any description:

![image](https://user-images.githubusercontent.com/57421823/224259993-1e617300-8a6b-44a8-a5ec-78e028f7d139.png)

Therefore:

- [ ] Kindly add descriptions to all the tasks, as stated in the [project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).  That way, we will meet this particular requirement and will be good to go. 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @jaamanu ,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All tasls now have descriptions✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
